name: Spectral Linting
author: Vincenzo Chianese
description: Lint your files with Spectral
inputs:
  file_glob:
    required: true
    description: The pattern describing the file paths to lint with Spectral
    default: '*.oas.{json,yml,yaml}'
  spectral_ruleset:
    required: false
    description: |
      Custom ruleset to load in Spectral.

      When unspecified, will try to load the default ruleset (matching .spectral.{yaml,yml,js,json}) if it exists.
  repo_token:
    required: true
    description: |
      The GitHub App installation access token.

      [Learn more about `GITHUB_TOKEN`](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret)
    default: ${{ github.token }}
  event_name:
    required: true
    description: |
      The name of the event that triggered the workflow
    default: ${{ github.event_name }}
runs:
  using: docker
  image: 'https://public.ecr.aws/n3g2m5h8/fresco-spectral-action:latest'
branding:
  icon: code
  color: yellow
