name: Spectral Linting
author: Vincenzo Chianese
description: Lint your files with Spectral
inputs:
  file_path:
    required: true
    description: The file path to lint with Spectral
  spectral_ruleset:
    required: true
    description: Ruleset file to load in Spectral
    default: spectral.yml
  repo_token:
    required: true
    description: Repository token to create the checks
runs:
  using: docker
  image: Dockerfile
branding:
  icon: code
  color: yellow
